[package]
name = "fizzbuzz-server"
version = "0.1.0"
authors = ["John Turner <while1malloc0@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
lazy_static = "1.4.0"
fizzbuzz = { path = "../fizzbuzz" }
metrics = { path = "../metrics" }
